services:
  - type: web
    name: simula-concurso
    env: node
    plan: free
    buildCommand: npm install && npm run prisma:deploy && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
